global using Services = EMS.PersonalInformation.gRPC.Services;
global using EMS.PersonalInformation.DAL.Database;
global using EMS.PersonalInformation.DAL.Repository;
global using EMS.PersonalInformation.Domain.Repository;
global using EMS.PersonalInformation.Domain.Services;
global using EMS.PersonalInformation.gRPC.RouteConfiguration;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using BllService = EMS.PersonalInformation.BLL.Services;
global using EMS.PersonalInformation.Domain.Models;
global using EMS.PersonalInformation.gRPC.Mapper;
global using EMS.PersonalInformation.gRPC.Protos.V1;
global using Grpc.Core;
global using static EMS.PersonalInformation.gRPC.Protos.V1.PersonalInformationService;
global using EMS.PersonalInformation.gRPC.Compression;
global using Grpc.Net.Compression;
global using System.IO.Compression;
global using Microsoft.Extensions.Caching.Distributed;
global using Newtonsoft.Json;