global using EmployeeManagementService.Domain.Models;
global using EmployeeManagementService.Domain.Repository;
global using EmployeeManagementService.Domain.Services;
global using EmployeeManagementService.Domain.Models.TrafficRecorderModels;